<?php

namespace Uerp\tpaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tpaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tpaymentRepository extends EntityRepository
{
}
