<?php

namespace Uerp\IncomesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * incomesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class incomesRepository extends EntityRepository
{
}
